version: "3.8"
services:
  backend:
    build: ./docker/php
    container_name: ${PROJECT_NAME}_backend
    image: ${PROJECT_NAME}_backend
    volumes:
      - ./backend:/work
      - ./docker/php/.msmtprc:/root/.msmtprc
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  web:
    build: ./docker/nginx
    container_name: ${PROJECT_NAME}_web
    image: ${PROJECT_NAME}_web
    ports:
      - 8000:80
    volumes:
      - ./backend:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build: ./docker/postgres
    container_name: ${PROJECT_NAME}_db
    image: ${PROJECT_NAME}_db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      TZ: Asia/Tokyo
      PGADMIN_DEFAULT_EMAIL: "aaa@bbb.ccc"
      PGADMIN_DEFAULT_PASSWORD: "pgpassword"

volumes:
  db-store:
    name: ${PROJECT_NAME}_pg_db-store
